### ISSUE TITLE
WesternImpl missing?

### ISSUE THREAD

**Issue by cfries** [AlessandroGnoatto/mafinlib#3]
https://github.com/AlessandroGnoatto/mafinlib/blob/f45726047d589c93a603a8a879dd2a3bbff6f846/mafinlib/src/org/mafinlib/time/calendars/UnitedStates.java#L176

Where is WesternImpl?

**Comment by AlessandroGnoatto** [comment]
Hi,

WesternImpl is defined in the general Calendar class. 

https://github.com/AlessandroGnoatto/mafinlib/blob/master/mafinlib/src/org/mafinlib/time/Calendar.java

From line 394.

In the same class you will find also OrthodoxImpl. These two provide an array containing the easter Monday for the Western and the Orthodox calender. I know you can subsitute the array with a function as you do in finmath. I do not know if there is something similiar also for the orthodox calendar however.

Hope this clarifies and thanks for having a look at the code.

**Comment by cfries** [comment]
OK. So WesternImp is an inner class! That was hard to find. I was looking for WeternImpl.java (expecting it to be a class). OrthodoxImpl is an inner class too and NyseImpl is an inner class of UnitedStates... I have to check out the project and use the IDE to find the implementation.

The concept is confusing to me. You can instantiate an object `Calendar`. Since the inner class `WesternImpl` is not static you _have_to_ instantiate the outer class object. The `Calendar` (outer) `this` holds a reverence to its inner class via `Impl impl`.  (Strange!)

Then Impl declares its fields as private, but the fields of Impl actually serve as member for the outer class (in addHoliday) (e.g. impl.removedHolidays.remove(d)) is accessing the private member of impl - it can do so, because it is its inner class. The implementation of add and remove is not Thread-Safe (first should use a ConcurrentHashMap, but the concept of mutable calendar is strange - what happens if a product schedule is generate by a calendar, then a date is added.

I believe Calendar object should be immutable. For construction there should be
a) pre-defined fixed calendars
b) single construction from a Set of given dates (we have to make the Set immutable - a TODO)
c) possibly a factory or builder ("getCalendarByName")
b) composition of calendars (as we already have).
